networks:
  todo-network:
    driver: bridge

services:
  todo-app:
    container_name: todo-app
    image: todo-app-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "8000:8000"
    volumes:
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - todo-network
